// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8Agu1k-dXJgDAZCU4yUfJj99lEk3NFr4',
    appId: '1:694977556417:web:043fd7b8934e26adf08940',
    messagingSenderId: '694977556417',
    projectId: 'landlordapp-9ae09',
    authDomain: 'landlordapp-9ae09.firebaseapp.com',
    storageBucket: 'landlordapp-9ae09.appspot.com',
    measurementId: 'G-057W2RW074',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWQ6yIO2kpFedxcRtQms3gL4RjSefZsVU',
    appId: '1:694977556417:android:a6c606eb5978e91ef08940',
    messagingSenderId: '694977556417',
    projectId: 'landlordapp-9ae09',
    storageBucket: 'landlordapp-9ae09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKf2EREyIiQBHoPceDm4mLYlAU8QFIV3s',
    appId: '1:694977556417:ios:61b07c3e3172b187f08940',
    messagingSenderId: '694977556417',
    projectId: 'landlordapp-9ae09',
    storageBucket: 'landlordapp-9ae09.appspot.com',
    iosBundleId: 'com.example.landlord.landlord',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKf2EREyIiQBHoPceDm4mLYlAU8QFIV3s',
    appId: '1:694977556417:ios:61b07c3e3172b187f08940',
    messagingSenderId: '694977556417',
    projectId: 'landlordapp-9ae09',
    storageBucket: 'landlordapp-9ae09.appspot.com',
    iosBundleId: 'com.example.landlord.landlord',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8Agu1k-dXJgDAZCU4yUfJj99lEk3NFr4',
    appId: '1:694977556417:web:6a3b053ba058d738f08940',
    messagingSenderId: '694977556417',
    projectId: 'landlordapp-9ae09',
    authDomain: 'landlordapp-9ae09.firebaseapp.com',
    storageBucket: 'landlordapp-9ae09.appspot.com',
    measurementId: 'G-7YW0NRYVE2',
  );

}